#ifdef __cplusplus 
extern "C" { 
#endif /* __cplusplus */ 

#ifndef TCAP_SNMP_AGENT_LOGENTITY_H
#define TCAP_SNMP_AGENT_LOGENTITY_H

#define TCAP_SNMP_AGENT_LOGENTITY  113

#define TTL_TCAPSNMPAGENT_FAILED_BAD_ARG 10
#define TTL_TCAPSNMPAGENT_FAILED_FILE_IO 11
#define TTL_TCAPSNMPAGENT_DSSDO_FAIL 12
#define TTL_TCAPSNMPAGENT_DSSDO_DATAERROR 13
#define TTL_TCAPSNMPAGENT_NOTCAP_INFO_STACK 14
#define TTL_TCAPSNMPAGENT_PROCESS_OID 15
#define TTL_TCAPSNMPAGENT_OID_NOTSUPP 16
#define TTL_TCAPSNMPAGENT_OID_NOTFOUND 17
#define TTL_TCAPSNMPAGENT_FAIL_AGENT 18

#endif /* TCAP_SNMP_AGENT_LOGENTITY_H */

#ifdef __cplusplus 
}
#endif /* __cplusplus */ 

